# name: Generate Snake

# on:
#   push:
#     branches: [main]
#   schedule:
#     - cron: "0 0 * * *"   # runs daily at midnight
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Generate Snake SVG
#         uses: Platane/snk@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: |
#                   dist/snake.svg?palette=github-dark
#                   dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b86e8,#3671c6

#       - name: Push to output branch
#         uses: peaceiris/actions-gh-pages@v4
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_branch: output
#           publish_dir: dist
#           force_orphan: true






name: Generate Snake

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b86e8,#3671c6

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
